<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bZemZkw' shared service.

return $this->privates['.service_locator.bZemZkw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::index' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::new' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\SecurityController::index' => ['privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController::status' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\VersementController::index' => ['privates', '.service_locator.e0UMJg.', 'get_ServiceLocator_E0UMJg_Service.php', true],
    'App\\Controller\\VersementController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController:index' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:new' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\SecurityController:index' => ['privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SecurityController:status' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\VersementController:index' => ['privates', '.service_locator.e0UMJg.', 'get_ServiceLocator_E0UMJg_Service.php', true],
    'App\\Controller\\VersementController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\PartenaireController::index' => '?',
    'App\\Controller\\PartenaireController::new' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\SecurityController::index' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\SecurityController::setViewHandler' => '?',
    'App\\Controller\\SecurityController::status' => '?',
    'App\\Controller\\VersementController::index' => '?',
    'App\\Controller\\VersementController::setViewHandler' => '?',
    'App\\Controller\\PartenaireController:index' => '?',
    'App\\Controller\\PartenaireController:new' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\SecurityController:index' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\SecurityController:setViewHandler' => '?',
    'App\\Controller\\SecurityController:status' => '?',
    'App\\Controller\\VersementController:index' => '?',
    'App\\Controller\\VersementController:setViewHandler' => '?',
]);
