<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e0UMJg.' shared service.

return $this->privates['.service_locator.e0UMJg.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'versementRepository' => ['privates', 'App\\Repository\\VersementRepository', 'getVersementRepositoryService.php', true],
], [
    'serializer' => '?',
    'versementRepository' => 'App\\Repository\\VersementRepository',
]);
