<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjdFJ4a\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjdFJ4a/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVjdFJ4a.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVjdFJ4a\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerVjdFJ4a\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'VjdFJ4a',
    'container.build_id' => '37826baa',
    'container.build_time' => 1564965350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjdFJ4a');
