<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEiu7FFx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEiu7FFx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEiu7FFx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEiu7FFx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEiu7FFx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Eiu7FFx',
    'container.build_id' => 'a38e609a',
    'container.build_time' => 1564414636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEiu7FFx');
