<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1LV9uOx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1LV9uOx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1LV9uOx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1LV9uOx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1LV9uOx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1LV9uOx',
    'container.build_id' => '64818785',
    'container.build_time' => 1564066917,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1LV9uOx');
