<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5NZ5lm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5NZ5lm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM5NZ5lm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM5NZ5lm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM5NZ5lm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M5NZ5lm',
    'container.build_id' => 'bb298197',
    'container.build_time' => 1567854651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5NZ5lm');
